### ISSUE TITLE
titlebar button styles + in-app theming are broken (csp error)

### ISSUE THREAD

**Issue by indolentbear** [notion-enhancer/desktop#291]
The position of the button to close the software is incorrect

![图片](https://user-images.githubusercontent.com/48911041/100517395-399f6d80-31c5-11eb-9e1a-1b4f0c68569f.png)

windows 10
Image resolution : 4k

**Comment by hjthjthjt** [comment]
On Windows 10 with 1080P, it happens too.
![image](https://user-images.githubusercontent.com/3889846/100543057-e42c9480-3288-11eb-9b31-7ce201e31ffe.png)

**Comment by indolentbear** [comment]
![图片](https://user-images.githubusercontent.com/48911041/100569746-eaaf2080-3309-11eb-90dd-5eb22972c6e0.png)

**Comment by dragonwocky** [comment]
this is a bug caused if notion is loaded with a strict content security policy - e.g. behind a school or work network. I've (finally!) found a fix and it will be part of v0.11.0 :)

**Comment by archetyped** [comment]
Looking forward to this fix.  No enhancer stylesheets are being loaded all of a sudden because of "Refused to load the stylesheet '<URL>' because it violates the following Content Security Policy " errors.

On the same network as 5 minutes ago (no changes to network either), but this issue started happening after I [reset Notion](https://www.notion.so/Reset-Notion-1b70196f1f6145d7a8695afc425d8699) (removing enhancer before resetting, and then re-applying enhancer post-reset).

**Comment by Akiriki** [comment]
Hey there, is it possible to somehow workaround this? 
It seems like the next release with the bugfix might still take some time, but sadly I cannot find any solution for this problem atm...

**Comment by dragonwocky** [comment]
@Akiriki it happens unreliably, so often just relaunching/restarting or trying a new network a couple times will fix it.

**Comment by hdecoded** [comment]
Facing the same issue. Enabling and disabling tabs removed the buttons altogether. 

Looks clean now 😁

**Comment by arjun-khatri** [comment]
> On Windows 10 with 1080P, it happens too.
> ![image](https://user-images.githubusercontent.com/3889846/100543057-e42c9480-3288-11eb-9b31-7ce201e31ffe.png)
> 
> Edit: Well, after restart Notion it goes well...

I restarted Notion several times now but it's still the same.

**Comment by lretr0l** [comment]
@dragonwocky uhm it's been almost two years since this issue was first found. can we even count on a new version? or is this deprecated?

**Comment by arjun-khatri** [comment]
> > On Windows 10 with 1080P, it happens too.
> > ![image](https://user-images.githubusercontent.com/3889846/100543057-e42c9480-3288-11eb-9b31-7ce201e31ffe.png)
> > Edit: Well, after restart Notion it goes well...
> 
> I restarted Notion several times now but it's still the same.

Installed it again and it's working fine now.

**Comment by dragonwocky** [comment]
@lretr0l ...that's not how time works. it's only been 6 months. that's not 2 years. the enhancer is not deprecated.
i have released attempts to fix this 3 times, and all of them have seemingly worked and then broken, which is why it's still open. updates are just slow because I don't have much time to work on the enhancer. (read: I'm busy with important stuff for school and nobody pays me to make the enhancer in my free time so I end up using a lot of my time on work).

**Comment by hdecoded** [comment]
Hey @dragonwocky, thanks for creating and maintaining this application. I understand and appreciate what you are doing for the notion community. Just wanted to thank you after seeing this comment.  

Cheers
HD

**Comment by Akiriki** [comment]
Yes same here, I am very grateful for this application / extension. This is a very huge upgrade for the notion client.
Thank you!

**Comment by lretr0l** [comment]
i apologize for sounding a bit rash, i don't know what i was thinking at the time. nevertheless, i am grateful to you and this project. keep up the good work!

**Comment by l782993610** [comment]
> this is a bug caused if notion is loaded with a strict content security policy - e.g. behind a school or work network. I've (finally!) found a fix and it will be part of v0.11.0 :)
> 
> edit: until then, since it happens unreliably, often just relaunching/restarting or trying a new network a couple times will fix it.

It happens reliably... I have try to restart or relaunch notion, or even reinstall notion and notion-enhance, but still not work. It's a very important bug, when will you release the pack for this problem.

**Comment by dragonwocky** [comment]
@l782993610 it is different for each user, it does not happen reliably. 

if i could, i would release it next week. unfortunately I'm currently busy with school and life to the point that I only have about 30 mins a week to work on the enhancer. so not anytime soon.

**Comment by l782993610** [comment]
> if i could, i would release it next week. unfortunately I'm currently busy with school and life to the point that I only have about 30 mins a week to work on the enhancer. so not anytime soon.

Okey. Thank you very much. And good news is that this problem disappear magically.
Restarting will not solve the problem. The process of solving this problem on my mac book is to reinstall Notion, and then reinstall Notion-enhancner. Turn on Notion and wait 5 minutes. Turn it off and wait 5 minutes. Then connect to the mobile network (not the campus network). Then it was solved. . .

**Comment by Hamzailer** [comment]
Any updates?

**Comment by PierrePDP** [comment]
Having the same issues with large icons.

**Comment by j-ong** [comment]
@dragonwocky managed to resolve this on Mac

Resources > app > embedded_enhancer > pkg > loader.js

Set bypassCSP to true on scheme notion

![Screenshot 2021-08-02 at 4 09 49 PM](https://user-images.githubusercontent.com/49931213/127826753-e4417cdb-acd6-4de0-8d98-bd0bac76578e.png)

**Comment by dragonwocky** [comment]
this should be fixed in https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-2

p.s. you will need to uninstall any/all versions of the notion app you currently have, then download the relevant file (e.g. a .exe) to reinstall the updated version

**Comment by hdecoded** [comment]
Hey @dragonwocky Just tested the issue and the integrated icons are still huge. uninstalled and reinstalled both notion and notion enhancer.

please let me know if I am missing anything

**Comment by yodaliu0414** [comment]
@dragonwocky , sorry to say that the bug is still there. 
![image](https://user-images.githubusercontent.com/50686783/130391635-f4df3f34-28dd-4256-b364-5d6bfa7b136f.png)
But when i use 'Tabs' features at the same time, it turns to be fixed.
![image](https://user-images.githubusercontent.com/50686783/130391735-1d3403e2-f7d8-4647-b312-99f427291658.png)

And the UI bug  in 'Word counter' features is still there also. Hope you can find a way to fix it. [(#541)](https://github.com/notion-enhancer/notion-enhancer/issues/541)
![image](https://user-images.githubusercontent.com/50686783/130392337-732e93ad-78b5-42ef-be30-cfe2344c2541.png)


Win10 with two screens, both are 1920x1080.

By the way, thank you for your great effort to create this magic plugin.

**Comment by metalzero24** [comment]
Tried this on a clean Windows 10 install (notion never installed before). Same big icons. You can reproduce it with a clean install virtual machine too I believe.

**Comment by dragonwocky** [comment]
@metalzero24 until the notion app cache is populated enough to ignore the content security policy, this bug will occur. (I don't understand entirely why a populated cache will ignore the csp, I just know it will.) - so a clean install will reliably fail, unfortunately.
a fix that actually works reliably from a clean install is work in progress and will be released soon.

**Comment by dragonwocky** [comment]
Try https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-3

**Comment by hdecoded** [comment]
Working as expected right now
